"""create planner block table

Revision ID: 85fca547e49d
Revises: 1553e4731772
Create Date: 2026-09-11 01:23:48.075121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85fca547e49d'
down_revision: Union[str, Sequence[str], None] = '1553e4731772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('block_type', sa.String(length=20), server_default='task', nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_blocks_block_type'), 'planner_blocks', ['block_type'], unique=False)
    op.create_index(op.f('ix_planner_blocks_is_completed'), 'planner_blocks', ['is_completed'], unique=False)
    op.create_index(op.f('ix_planner_blocks_planned_date'), 'planner_blocks', ['planned_date'], unique=False)
    op.create_index(op.f('ix_planner_blocks_task_id'), 'planner_blocks', ['task_id'], unique=False)
    op.create_index(op.f('ix_planner_blocks_user_id'), 'planner_blocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planner_blocks_user_id'), table_name='planner_blocks')
    op.drop_index(op.f('ix_planner_blocks_task_id'), table_name='planner_blocks')
    op.drop_index(op.f('ix_planner_blocks_planned_date'), table_name='planner_blocks')
    op.drop_index(op.f('ix_planner_blocks_is_completed'), table_name='planner_blocks')
    op.drop_index(op.f('ix_planner_blocks_block_type'), table_name='planner_blocks')
    op.drop_table('planner_blocks')
    # ### end Alembic commands ###
